# Generated by Django 4.0.2 on 2022-09-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author',
        ),
    ]
