# Generated by Django 4.0.2 on 2022-09-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_remove_message_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
